---
name: Test collection
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-build:
    uses: Qalthos/github_actions/.github/workflows/build.yml@dependencies

  sanity:
    needs: pre-build
    uses: Qalthos/github_actions/.github/workflows/sanity.yml@dependencies

  unit:
    needs: pre-build
    uses: Qalthos/github_actions/.github/workflows/unit.yml@dependencies
